#this file must be located in config/ci-config.yaml
executables: 
  php5:    /Applications/MAMP/bin/php5/bin/php                         
  php4:    /Applications/MAMP/bin/php4/bin/php 
  phpunit: phpunit

environments:                          
  mysql:    mysql-testing              # will look for config/mysql-testing.php
  postgres: postgres-testing
  sqlite:   sqlite-testing

default_executables: 
  - php5 
  - php4

valid_combinations:  
  php4: 
    - mysql
    - postgres
    
  php5: 
    - mysql
    - postgres
    - sqlite

